name: Transcribe URL

on:
  repository_dispatch:
    types: [transcribe-event]

jobs:
  transcribe:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/maitreyabuddha/transcribe:main
    steps:
      - name: Transcribe
        run: transcribe-anything '${{ github.event.client_payload.transcribeUrl }}'
