name: Transcribe URL

on:
  repository_dispatch:
    types: [transcribe-event]

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - id: lower-repo
        run: |
          echo "IMAGE_TAG=ghcr.io/${GITHUB_REPOSITORY@L}:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Run transcribe container
        uses: docker://${IMAGE_TAG}
        with:
          args: transcribe-anything '${{ github.event.client_payload.transcribeUrl }}'
